# Generated by Django 2.2.4 on 2019-09-23 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_produto_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='marca',
        ),
    ]
